# Generated by Django 5.2.9 on 2025-12-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmake',
            name='country',
        ),
    ]
